- type: entity
  id: MedievalSawmillDetail
  parent: MedievalBaseMachineDetail
  name: деталь пилорамы
  components:
  - type: MachineBoard
    prototype: MedievalSawmill
  - type: PhysicalComposition
    materialComposition:
      MedievalProcessedWood: 4

- type: entity
  id: MedievalCarpenterTableDetail
  parent: MedievalBaseMachineDetail
  name: деталь стола плотника
  components:
  - type: MachineBoard
    prototype: MedievalCarpenterTable
  - type: PhysicalComposition
    materialComposition:
      MedievalProcessedWood: 3

- type: entity
  id: MedievalSmelterDetail
  parent: MedievalBaseMachineDetail
  name: деталь плавильни
  components:
  - type: MachineBoard
    prototype: MedievalSmelter
  - type: PhysicalComposition
    materialComposition:
      MedievalProcessedStone: 5

- type: entity
  id: MedievalAlchemTableDetail
  parent: MedievalBaseMachineDetail
  name: деталь алхимического стола
  components:
  - type: MachineBoard
    prototype: MedievalAlchemTable
  - type: PhysicalComposition
    materialComposition:
      MedievalProcessedWood: 4

- type: entity
  id: MedievalReagentGrinderDetail
  parent: MedievalBaseMachineDetail
  name: деталь измельчителя
  components:
  - type: MachineBoard
    prototype: MedievalReagentGrinder
  - type: PhysicalComposition
    materialComposition:
      MedievalProcessedWood: 2

- type: entity
  id: MedievalHotplateDetail
  parent: MedievalBaseMachineDetail
  name: деталь костровой жаровни
  components:
  - type: MachineBoard
    prototype: MedievalHotplate
  - type: PhysicalComposition
    materialComposition:
      MedievalProcessedWood: 1

